"""enforce unique workspace membership

Revision ID: a04f5c08be7f
Revises: 5bb35abd48d1
Create Date: 2026-08-19 17:23:13.055224

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a04f5c08be7f'
down_revision: str | Sequence[str] | None = '5bb35abd48d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workspace_members_workspace_user', 'workspace_members', ['workspace_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_members_workspace_user', 'workspace_members', type_='unique')
    # ### end Alembic commands ###
